import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { TenantProvider } from "@/components/TenantContext";
import { RoleProvider } from "@/components/RoleContext";
import { LoaderProvider } from "@/components/LoaderContext";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased bg-gray-100`}
      >
        <LoaderProvider>
          <TenantProvider>
            <RoleProvider>
              <SidebarProvider>
                <AppSidebar />
                <SidebarTrigger className="scale-125 rounded-full m-2" />
                {children}
              </SidebarProvider>
            </RoleProvider>
          </TenantProvider>
        </LoaderProvider>
      </body>
    </html>
  );
}
